image: Visual Studio 2017
version: 0.1.0.{build}

environment:
  packageVersion: 0.1.0

skip_branch_with_pr: true

init:
  - ps: $env:buildVersion = "$env:packageVersion"
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "false") { $env:buildVersion = "$env:packageVersion-alpha$env:APPVEYOR_BUILD_NUMBER" }
  - ps: Update-AppveyorBuild -Version $env:buildVersion

dotnet_csproj:
  patch: true
  file: 'CalDAV.NET\CalDAV.NET.csproj'
  version: $env:buildVersion
  package_version: $env:buildVersion
  assembly_version: $env:buildVersion

before_build:
  - nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true

artifacts:
  - path: /.*\.nupkg/

deploy:
  - provider: NuGet
    api_key:
      secure: l779ntBLoBFfEkRn83YwoOs/CA15RoQlt1BXLRB0PczcwhfMZChzaCwgO4qI8OLN
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master
